# Get Top Rated Movies
GET https://api.themoviedb.org/3/movie/top_rated?api_key=883ee274b7ce2d49978875c3d25de159&page=2

###
# Search Movie
GET https://api.themoviedb.org/3/search/movie?api_key=883ee274b7ce2d49978875c3d25de159&query=avengers

###
# Get Movie Detail
GET https://api.themoviedb.org/3/movie/448368?api_key=883ee274b7ce2d49978875c3d25de159

### 
# Get Genre List
GET https://api.themoviedb.org/3/genre/movie/list?api_key=883ee274b7ce2d49978875c3d25de159

### 
# Get Movie Video
GET https://api.themoviedb.org/3/movie/448368/videos?api_key=883ee274b7ce2d49978875c3d25de159
